import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { fmtUSD } from "./utils";
import { fmtRange } from "./estimator-rates";
import type { EstimateResult, PricedPhase } from "./estimator-rates";

// Re-exported so callers keep importing the estimate shape from the module that
// renders it; the numbers themselves are defined in ./estimator-rates.
export type { EstimateResult, PricedPhase as BreakdownRow };

type Answers = Record<string, string>;

export function buildEstimatePDF(result: EstimateResult, answers: Answers): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const PW  = doc.internal.pageSize.getWidth();
  const PH  = doc.internal.pageSize.getHeight();
  const ML  = 18;
  const MR  = PW - 18;
  const rows = result.breakdown.filter((r) => r.hours > 0);

  const C = {
    ink:      [15,  23,  42]  as [number, number, number],
    muted:    [100, 116, 139] as [number, number, number],
    blue:     [59,  130, 246] as [number, number, number],
    blueBg:   [239, 246, 255] as [number, number, number],
    emerald:  [16,  185, 129] as [number, number, number],
    border:   [226, 232, 240] as [number, number, number],
    white:    [255, 255, 255] as [number, number, number],
    headerBg: [30,  58, 138]  as [number, number, number],
  };

  const money = fmtUSD;

  const setFont = (style: "normal" | "bold" | "italic" = "normal", size = 10, color = C.ink) => {
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    doc.setTextColor(...color);
  };

  const addWatermark = () => {
    const pages = doc.getNumberOfPages();
    for (let p = 1; p <= pages; p++) {
      doc.setPage(p);
      doc.saveGraphicsState();
      doc.setGState(new (doc as unknown as { GState: new (o: { opacity: number }) => unknown }).GState({ opacity: 0.08 }));
      doc.setFont("helvetica", "bold");
      doc.setFontSize(25);
      doc.setTextColor(30, 58, 138);
      doc.text("generated by kathanpatel.vercel.app", PW / 2, PH / 2, { align: "center", angle: 45 });
      doc.restoreGraphicsState();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(...C.muted);
      doc.text("generated by kathanpatel.vercel.app", PW / 2, PH - 8, { align: "center" });
      doc.setDrawColor(...C.border);
      doc.line(ML, PH - 11, MR, PH - 11);
    }
  };

  let y = 0;

  // The sections below are positioned by hand, so a long brief or a wide set of
  // assumptions would otherwise run off the page. autoTable paginates itself.
  const ensureSpace = (needed: number) => {
    if (y + needed > PH - 18) {
      doc.addPage();
      y = 20;
    }
  };

  const sectionHeading = (label: string, ruleWidth: number) => {
    ensureSpace(16);
    setFont("bold", 8, C.muted);
    doc.setCharSpace(1.2);
    doc.text(label, ML, y);
    doc.setCharSpace(0);
    y += 3;
    doc.setDrawColor(...C.blue);
    doc.setLineWidth(0.8);
    doc.line(ML, y, ML + ruleWidth, y);
    y += 5;
  };

  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, PW, 38, "F");

  setFont("bold", 18, C.white);
  doc.text("Project Cost Estimate", ML, 16);

  setFont("normal", 9, [186, 210, 255]);
  doc.text("AI-generated estimate · kathanpatel.vercel.app", ML, 24);

  const now = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  doc.text(now, MR, 24, { align: "right" });

  y = 46;

  doc.setFillColor(...C.blueBg);
  doc.roundedRect(ML, y, PW - 36, 22, 4, 4, "F");
  doc.setDrawColor(...C.blue);
  doc.setLineWidth(0.4);
  doc.roundedRect(ML, y, PW - 36, 22, 4, 4, "S");

  setFont("normal", 8, C.muted);
  doc.text("ESTIMATED PROJECT COST", PW / 2, y + 6, { align: "center" });

  setFont("bold", 20, C.blue);
  doc.text(`${money(result.hourly.low)} – ${money(result.hourly.high)}`, PW / 2, y + 16, { align: "center" });

  y += 27;
  setFont("normal", 7.5, C.muted);
  doc.text(
    `${fmtRange(result.hours.low, result.hours.high)} working hours · includes ${Math.round(result.buffer_pct * 100)}% contingency for revisions & scope creep`,
    PW / 2,
    y,
    { align: "center" },
  );
  y += 4.5;
  doc.text(
    `Indicative timeline: ${fmtRange(result.timeline.low.full_time_weeks, result.timeline.high.full_time_weeks)} weeks full-time, `
      + `or ${fmtRange(result.timeline.low.part_time_weeks, result.timeline.high.part_time_weeks)} weeks part-time`,
    PW / 2,
    y,
    { align: "center" },
  );
  y += 10;

  sectionHeading("PROJECT DETAILS", 36);

  const details: [string, string][] = (
    [
      ["Stack",  answers.techStack],
      ["Budget", answers.budget],
    ] as [string, string | undefined][]
  ).filter((pair): pair is [string, string] => Boolean(pair[1]));

  details.forEach(([label, value]) => {
    setFont("bold", 9, C.ink);
    doc.text(`${label}:`, ML, y);
    setFont("normal", 9, C.ink);
    doc.text(value, ML + 28, y);
    y += 6;
  });

  if (answers.description) {
    setFont("bold", 9, C.ink);
    doc.text("Description:", ML, y);
    y += 5;
    setFont("normal", 8.5, C.muted);
    // Clamp long briefs so the manually positioned sections never run off the page
    const wrapped = doc.splitTextToSize(answers.description, PW - 36) as string[];
    const MAX_DESC_LINES = 12;
    // Drop the trailing word (not just a character) so the ellipsis never splits a word
    const lines = wrapped.length > MAX_DESC_LINES
      ? [...wrapped.slice(0, MAX_DESC_LINES - 1), wrapped[MAX_DESC_LINES - 1].replace(/\s*\S+\s*$/, "") + " …"]
      : wrapped;
    doc.text(lines, ML, y);
    y += lines.length * 4.8 + 3;
  }

  y += 4;

  sectionHeading("AI SUMMARY", 28);

  setFont("normal", 8.5, C.ink);
  const summaryLines = doc.splitTextToSize(result.summary, PW - 36) as string[];
  ensureSpace(summaryLines.length * 4.8);
  doc.text(summaryLines, ML, y);
  y += summaryLines.length * 4.8 + 8;

  // What the AI assumed to reach these hours — printed so a wrong assumption is
  // visible and correctable rather than buried inside the total.
  if (result.scope_assumptions.length > 0) {
    sectionHeading("SCOPE ASSUMPTIONS", 44);

    setFont("normal", 8.5, C.ink);
    result.scope_assumptions.forEach((item) => {
      const lines = doc.splitTextToSize(item, PW - 42) as string[];
      ensureSpace(lines.length * 4.6 + 2);
      doc.text("•", ML, y);
      doc.text(lines, ML + 4, y);
      y += lines.length * 4.6 + 1.5;
    });
    y += 6;
  }

  sectionHeading("COST BREAKDOWN", 38);
  y -= 1;

  autoTable(doc, {
    startY: y,
    margin: { left: ML, right: 18 },
    head: [["Phase", "Hours", "Rate", "Cost"]],
    body: [
      ...rows.map((r) => [
        r.tier === "specialist" ? `${r.phase} †` : r.phase,
        `${r.hours}h`,
        `$${r.rate}/hr`,
        money(r.cost),
      ]),
      [
        { content: `Total (${result.hours.low}h)`, colSpan: 3, styles: { fontStyle: "bold" } },
        money(result.hourly.low),
      ],
    ],
    headStyles: {
      fillColor:  C.headerBg,
      textColor:  C.white,
      fontStyle:  "bold",
      fontSize:   8,
      halign:     "left",
    },
    columnStyles: {
      0: { cellWidth: "auto" },
      1: { halign: "right", textColor: C.muted, fontSize: 8 },
      2: { halign: "right", textColor: C.muted, fontSize: 8 },
      3: { halign: "right", textColor: C.emerald, fontStyle: "bold", fontSize: 8.5 },
    },
    bodyStyles:   { fontSize: 8.5, textColor: C.ink },
    alternateRowStyles: { fillColor: [248, 250, 252] as [number, number, number] },
    tableLineColor: C.border,
    tableLineWidth: 0.3,
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5;

  if (rows.some((r) => r.tier === "specialist")) {
    setFont("normal", 7, C.muted);
    doc.text(
      "† Specialist work — AI/LLM, real-time or multi-tenant architecture, payment & compliance integrations.",
      ML,
      y,
    );
    y += 5;
  }
  y += 5;

  // Longer projects get the retainer option, where a committed month costs less
  // per hour than billing the same work hourly.
  if (result.monthly) {
    ensureSpace(30);
    doc.setFillColor(...C.blueBg);
    doc.roundedRect(ML, y, PW - 36, 24, 3, 3, "F");

    setFont("bold", 8.5, C.ink);
    doc.text("Alternative: monthly engagement", ML + 5, y + 7);

    setFont("normal", 8, C.muted);
    doc.text(
      `${fmtRange(result.monthly.months_low, result.monthly.months_high)} months at ${money(result.monthly.rate)}/month `
        + `(${result.monthly.hours_per_month}h/month, $${result.monthly.effective_hourly}/hr effective)`,
      ML + 5,
      y + 13,
    );

    setFont("bold", 8, C.emerald);
    doc.text(
      `${money(result.monthly.low)} – ${money(result.monthly.high)} · saves ${money(result.monthly.saving_vs_hourly)} versus hourly`,
      ML + 5,
      y + 19,
    );
    y += 32;
  }

  if (result.risks.length > 0) {
    sectionHeading("KEY RISKS", 26);

    setFont("normal", 8.5, C.ink);
    result.risks.forEach((risk) => {
      const lines = doc.splitTextToSize(risk, PW - 42) as string[];
      ensureSpace(lines.length * 4.6 + 2);
      doc.text("•", ML, y);
      doc.text(lines, ML + 4, y);
      y += lines.length * 4.6 + 1.5;
    });
    y += 6;
  }

  if (result.recommended_stack) {
    sectionHeading("RECOMMENDED STACK", 44);
    setFont("normal", 8.5, C.ink);
    const stackLines = doc.splitTextToSize(result.recommended_stack, PW - 36) as string[];
    ensureSpace(stackLines.length * 4.8);
    doc.text(stackLines, ML, y);
  }

  addWatermark();
  return doc;
}

export function estimatePDFBase64(result: EstimateResult, answers: Answers): string {
  const doc = buildEstimatePDF(result, answers);
  return doc.output("datauristring").split(",")[1] ?? "";
}
