import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { fmtUSD } from "./utils";

export interface BreakdownRow {
  phase: string;
  hours: number;
  rate: number;
  cost: number;
}

export interface EstimateResult {
  range_low: number;
  range_high: number;
  summary: string;
  breakdown: BreakdownRow[];
  risks: string[];
  recommended_stack: string;
}

type Answers = Record<string, string>;

export function buildEstimatePDF(result: EstimateResult, answers: Answers): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const PW  = doc.internal.pageSize.getWidth();
  const PH  = doc.internal.pageSize.getHeight();
  const ML  = 18;
  const MR  = PW - 18;
  const totalBase = result.breakdown.reduce((s, r) => s + r.cost, 0);

  const C = {
    ink:      [15,  23,  42]  as [number, number, number],
    muted:    [100, 116, 139] as [number, number, number],
    blue:     [59,  130, 246] as [number, number, number],
    blueBg:   [239, 246, 255] as [number, number, number],
    emerald:  [16,  185, 129] as [number, number, number],
    border:   [226, 232, 240] as [number, number, number],
    white:    [255, 255, 255] as [number, number, number],
    headerBg: [30,  58, 138]  as [number, number, number],
  };

  const money = fmtUSD;

  const setFont = (style: "normal" | "bold" | "italic" = "normal", size = 10, color = C.ink) => {
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    doc.setTextColor(...color);
  };

  const addWatermark = () => {
    const pages = doc.getNumberOfPages();
    for (let p = 1; p <= pages; p++) {
      doc.setPage(p);
      doc.saveGraphicsState();
      doc.setGState(new (doc as unknown as { GState: new (o: { opacity: number }) => unknown }).GState({ opacity: 0.08 }));
      doc.setFont("helvetica", "bold");
      doc.setFontSize(25);
      doc.setTextColor(30, 58, 138);
      doc.text("generated by kathanpatel.vercel.app", PW / 2, PH / 2, { align: "center", angle: 45 });
      doc.restoreGraphicsState();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(...C.muted);
      doc.text("generated by kathanpatel.vercel.app", PW / 2, PH - 8, { align: "center" });
      doc.setDrawColor(...C.border);
      doc.line(ML, PH - 11, MR, PH - 11);
    }
  };

  let y = 0;

  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, PW, 38, "F");

  setFont("bold", 18, C.white);
  doc.text("Project Cost Estimate", ML, 16);

  setFont("normal", 9, [186, 210, 255]);
  doc.text("AI-generated estimate · kathanpatel.vercel.app", ML, 24);

  const now = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  doc.text(now, MR, 24, { align: "right" });

  y = 46;

  doc.setFillColor(...C.blueBg);
  doc.roundedRect(ML, y, PW - 36, 22, 4, 4, "F");
  doc.setDrawColor(...C.blue);
  doc.setLineWidth(0.4);
  doc.roundedRect(ML, y, PW - 36, 22, 4, 4, "S");

  setFont("normal", 8, C.muted);
  doc.text("ESTIMATED PROJECT COST", PW / 2, y + 6, { align: "center" });

  setFont("bold", 20, C.blue);
  doc.text(`${money(result.range_low)} – ${money(result.range_high)}`, PW / 2, y + 16, { align: "center" });

  y += 27;
  setFont("normal", 7.5, C.muted);
  doc.text("Includes 20% overhead for PM, QA & scope buffer", PW / 2, y, { align: "center" });
  y += 10;

  setFont("bold", 8, C.muted);
  doc.setCharSpace(1.2);
  doc.text("PROJECT DETAILS", ML, y);
  doc.setCharSpace(0);
  y += 3;
  doc.setDrawColor(...C.blue);
  doc.setLineWidth(0.8);
  doc.line(ML, y, ML + 36, y);
  y += 5;

  const details: [string, string][] = (
    [
      ["Stack",  answers.techStack],
      ["Budget", answers.budget],
    ] as [string, string | undefined][]
  ).filter((pair): pair is [string, string] => Boolean(pair[1]));

  details.forEach(([label, value]) => {
    setFont("bold", 9, C.ink);
    doc.text(`${label}:`, ML, y);
    setFont("normal", 9, C.ink);
    doc.text(value, ML + 28, y);
    y += 6;
  });

  if (answers.description) {
    setFont("bold", 9, C.ink);
    doc.text("Description:", ML, y);
    y += 5;
    setFont("normal", 8.5, C.muted);
    // Clamp long briefs so the manually positioned sections never run off the page
    const wrapped = doc.splitTextToSize(answers.description, PW - 36) as string[];
    const MAX_DESC_LINES = 12;
    // Drop the trailing word (not just a character) so the ellipsis never splits a word
    const lines = wrapped.length > MAX_DESC_LINES
      ? [...wrapped.slice(0, MAX_DESC_LINES - 1), wrapped[MAX_DESC_LINES - 1].replace(/\s*\S+\s*$/, "") + " …"]
      : wrapped;
    doc.text(lines, ML, y);
    y += lines.length * 4.8 + 3;
  }

  y += 4;

  setFont("bold", 8, C.muted);
  doc.setCharSpace(1.2);
  doc.text("AI SUMMARY", ML, y);
  doc.setCharSpace(0);
  y += 3;
  doc.setDrawColor(...C.blue);
  doc.setLineWidth(0.8);
  doc.line(ML, y, ML + 28, y);
  y += 5;

  setFont("normal", 8.5, C.ink);
  const summaryLines = doc.splitTextToSize(result.summary, PW - 36);
  doc.text(summaryLines, ML, y);
  y += summaryLines.length * 4.8 + 8;

  setFont("bold", 8, C.muted);
  doc.setCharSpace(1.2);
  doc.text("COST BREAKDOWN", ML, y);
  doc.setCharSpace(0);
  y += 3;
  doc.setDrawColor(...C.blue);
  doc.setLineWidth(0.8);
  doc.line(ML, y, ML + 38, y);
  y += 4;

  autoTable(doc, {
    startY: y,
    margin: { left: ML, right: 18 },
    head: [["Phase", "Hours", "Rate", "Cost"]],
    body: [
      ...result.breakdown.map((r) => [
        r.phase,
        `${r.hours}h`,
        `$${r.rate}/hr`,
        money(r.cost),
      ]),
      [{ content: "Base total", colSpan: 3, styles: { fontStyle: "bold" } }, money(totalBase)],
    ],
    headStyles: {
      fillColor:  C.headerBg,
      textColor:  C.white,
      fontStyle:  "bold",
      fontSize:   8,
      halign:     "left",
    },
    columnStyles: {
      0: { cellWidth: "auto" },
      1: { halign: "right", textColor: C.muted, fontSize: 8 },
      2: { halign: "right", textColor: C.muted, fontSize: 8 },
      3: { halign: "right", textColor: C.emerald, fontStyle: "bold", fontSize: 8.5 },
    },
    bodyStyles:   { fontSize: 8.5, textColor: C.ink },
    alternateRowStyles: { fillColor: [248, 250, 252] as [number, number, number] },
    tableLineColor: C.border,
    tableLineWidth: 0.3,
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;

  if (result.recommended_stack) {
    setFont("bold", 8, C.muted);
    doc.setCharSpace(1.2);
    doc.text("RECOMMENDED STACK", ML, y);
    doc.setCharSpace(0);
    y += 8;
    setFont("normal", 8.5, C.ink);
    const stackLines = doc.splitTextToSize(result.recommended_stack, PW - 36);
    doc.text(stackLines, ML, y);
  }

  addWatermark();
  return doc;
}

export function estimatePDFBase64(result: EstimateResult, answers: Answers): string {
  const doc = buildEstimatePDF(result, answers);
  return doc.output("datauristring").split(",")[1] ?? "";
}
